on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true # Ensure credentials persist for further Git commands

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.5.0 # Use the desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          npm run build
