on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Use the desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build and Deploy
        run: npm run deploy
